### ISSUE TITLE
Installing kohana-phpexcel in Kohana 3.3.0

### ISSUE THREAD

**Issue by oaloria** [dshovchko/kohana-phpexcel#1]
I have installed kohana-excel in Kohana 3.3.0
The modification is pretty easy, so I think you could include it in your module
it will helps someone.

This is my email: oaloria@gmail.com

**Comment by dshovchko** [comment]
Hello, Oscar!

Thank you so much!
Please send your patch, I'll update module.

2013/1/15 Oscar notifications@github.com

> I have installed kohana-excel in Kohana 3.3.0
> The modification is pretty easy, so I think you could include it in your
> module
> it will helps someone.
> 
> This is my email: oaloria@gmail.com
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dshovchko/kohana-phpexcel/issues/1.

## 

With best regards, Dmitry Shovchko.  E-mail: d.shovchko@gmail.com

**Comment by oaloria** [comment]
Hello Dmitry.

I'm not an expert in Kohana but I know some things.

What I did to have kohana-phpexcel module working on Kohana 3.3.0
is a little change in method send in classes/spreadsheet.php

I just change the original send method for this:

``` javascript
public function send($settings=array())
{
    $settings = array_merge(array(
        'format' => 'Excel2007',
        'name' => 'NewSpreadsheet',
     ), $settings);

    $writer = PHPExcel_IOFactory::createWriter($this->_spreadsheet, $settings['format']);

    $ext = $this->exts[$settings['format']];
    $mime = $this->mimes[$settings['format']];

    if ($settings['format'] == 'CSV')
    {
        $writer->setUseBOM(true);
    }

    Response::factory()->body( $writer->save('php://output') );
    Response::factory()->send_file( true, $settings['name'].'.'.$ext );
    exit;
}
```

 /_Old Code_/
//$request = Request::current();
//$request->headers['Content-Type'] = $mime;
//$request->headers['Content-Disposition'] = 'attachment;filename="'.$settings['name'].'.'.$ext.'"';
//$request->headers['Cache-Control'] = 'max-age=0';
//$request->send_headers();

My github user is oaloria, if you have some question.

Thanks, Oscar Loría.

2013/1/16 Dmitry Shovchko notifications@github.com
